<?php

namespace Balancenet\Bundle\ScrapyBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SchedulerRuntimeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SchedulerRuntimeRepository extends EntityRepository
{
}
