<?php

namespace Balancenet\Bundle\ScrapyBundle\Entity\Repository;

use Doctrine\ORM\Query;
use Doctrine\ORM\EntityRepository;

/**
 * ScraperElementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScrapedProductRepository extends EntityRepository
{
}
