datagrid:
    #ScrapedObjClass Grid
    scrapedobjclass-grid:
        extended_entity_name: %balancenet_scrapy.entity.scrapedobjclass.class%
        options:
            entityHint: scrapedobjclass
        source:
            acl_resource: oro_user_user_view
            type: orm
            query:
                select:
                    - f.id
                    - f.name
                from:
                    - { table: %balancenet_scrapy.entity.scrapedobjclass.class%, alias: f }
        columns:
            name:
                label: balanenet.scrapedobjclass.name.label

        properties:
            id: ~
            update_link:
                type: url
                route: balancenet_scrapy_scrapedobjclass_update
                params:
                    - id
            view_link:
                type: url
                route: balancenet_scrapy_scrapedobjclass_view
                params:
                    - id
            delete_link:
                type: url
                route: oro_api_delete_user
                params:
                    - id
        sorters:
            columns:
                name:
                    data_name: f.name
            default:
                username: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC

        filters:
            columns:

        actions:
            view:
                type:          navigate
                acl_resource:  balancenet_scrapy_scrapedobjclass_view
                label:         View
                icon:          user
                link:          view_link
                rowAction:     true
            update:
                type:          navigate
                acl_resource:  balancenet_scrapy_scrapedobjclass_update
                label:         Update
                icon:          edit
                link:          update_link
            delete:
                type:          delete
                acl_resource:  balancenet_scrapy_scrapedobjclass_delete
                label:         Delete
                icon:          trash
                link:          delete_link
    #Scraper Grid
    scraper-grid:
        extended_entity_name: %balancenet_scrapy.entity.scraper.class%
        options:
            entityHint: scraper
        source:
            acl_resource: oro_user_user_view
            type: orm
            query:
                select:
                    - f.id
                    - f.name
                from:
                    - { table: %balancenet_scrapy.entity.scraper.class%, alias: f }
        columns:
            name:
                label: balanenet.scraper.name.label

        properties:
            id: ~
            update_link:
                type: url
                route: balancenet_scrapy_scraper_update
                params:
                    - id
            view_link:
                type: url
                route: balancenet_scrapy_scraper_update
                params:
                    - id
            delete_link:
                type: url
                route: oro_api_delete_user
                params:
                    - id
        sorters:
            columns:
                name:
                    data_name: f.name
            default:
                username: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC

        filters:
            columns:

        actions:
            view:
                type:          navigate
                acl_resource:  balancenet_scrapy_scrapyer_view
                label:         View
                icon:          user
                link:          view_link
                rowAction:     true
            update:
                type:          navigate
                acl_resource:  balancenet_scrapy_scrapyer_update
                label:         Update
                icon:          edit
                link:          update_link
            delete:
                type:          delete
                acl_resource:  balancenet_scrapy_scrapyer_delete
                label:         Delete
                icon:          trash
                link:          delete_link
    #Site Grid
    site-grid:
        extended_entity_name: %balancenet_scrapy.entity.site.class%
        options:
            entityHint: site
        source:
            acl_resource: oro_user_user_view
            type: orm
            query:
                select:
                    - f.id
                    - f.name
                from:
                    - { table: %balancenet_scrapy.entity.site.class%, alias: f }
        columns:
            name:
                label: balanenet.site.name.label

        properties:
            id: ~
            update_link:
                type: url
                route: balancenet_scrapy_site_update
                params:
                    - id
            view_link:
                type: url
                route: balancenet_scrapy_site_view
                params:
                    - id
            delete_link:
                type: url
                route: oro_api_delete_user
                params:
                    - id
        sorters:
            columns:
                name:
                    data_name: f.name
            default:
                username: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC

        filters:
            columns:

        actions:
            view:
                type:          navigate
                acl_resource:  balancenet_scrapy_site_view
                label:         View
                icon:          user
                link:          view_link
                rowAction:     true
            update:
                type:          navigate
                acl_resource:  balancenet_scrapy_site_update
                label:         Update
                icon:          edit
                link:          update_link
            delete:
                type:          delete
                acl_resource:  balancenet_scrapy_site_delete
                label:         Delete
                icon:          trash
                link:          delete_link
    #Product Grid
    product-grid:
        extended_entity_name: %balancenet_scrapy.entity.product.class%
        options:
            entityHint: product
        source:
            acl_resource: oro_user_user_view
            type: orm
            query:
                select:
                    - f.id
                    - f.name
                from:
                    - { table: %balancenet_scrapy.entity.product.class%, alias: f }
        columns:
            name:
                label: balanenet.product.name.label

        properties:
            id: ~
            update_link:
                type: url
                route: balancenet_scrapy_product_update
                params:
                    - id
            view_link:
                type: url
                route: balancenet_scrapy_product_view
                params:
                    - id
            delete_link:
                type: url
                route: oro_api_delete_user
                params:
                    - id
        sorters:
            columns:
                name:
                    data_name: f.name
            default:
                username: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC

        filters:
            columns:

        actions:
            view:
                type:          navigate
                acl_resource:  balancenet_scrapy_product_view
                label:         View
                icon:          user
                link:          view_link
                rowAction:     true
            update:
                type:          navigate
                acl_resource:  balancenet_scrapy_product_update
                label:         Update
                icon:          edit
                link:          update_link
            delete:
                type:          delete
                acl_resource:  balancenet_scrapy_product_delete
                label:         Delete
                icon:          trash
                link:          delete_link
    #SchedulerRuntime Grid
    schedulerruntime-grid:
        extended_entity_name: %balancenet_scrapy.entity.schedulerruntime.class%
        options:
            entityHint: schedulerruntime
        source:
            acl_resource: oro_user_user_view
            type: orm
            query:
                select:
                    - f.id
                    - f.runtimeType
                from:
                    - { table: %balancenet_scrapy.entity.schedulerruntime.class%, alias: f }
        columns:
            name:
                label: balanenet.schedulerruntime.name.label

        properties:
            id: ~
            update_link:
                type: url
                route: balancenet_scrapy_schedulerruntime_update
                params:
                    - id
            view_link:
                type: url
                route: balancenet_scrapy_schedulerruntime_view
                params:
                    - id
            delete_link:
                type: url
                route: oro_api_delete_user
                params:
                    - id
        sorters:
            columns:
                name:
                    data_name: f.name
            default:
                username: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC

        filters:
            columns:

        actions:
            view:
                type:          navigate
                acl_resource:  balancenet_scrapy_monitor_view
                label:         View
                icon:          user
                link:          view_link
                rowAction:     true
            update:
                type:          navigate
                acl_resource:  balancenet_scrapy_monitor_update
                label:         Update
                icon:          edit
                link:          update_link
            delete:
                type:          delete
                acl_resource:  balancenet_scrapy_monitor_delete
                label:         Delete
                icon:          trash
                link:          delete_link
    #History Grid
    history-grid:
        extended_entity_name: %balancenet_scrapy.entity.history.class%
        options:
            entityHint: history
        source:
            acl_resource: oro_user_user_view
            type: orm
            query:
                select:
                    - f.id
                    - f.message
                from:
                    - { table: %balancenet_scrapy.entity.history.class%, alias: f }
        columns:
            name:
                label: balanenet.history.name.label

        properties:
            id: ~
            update_link:
                type: url
                route: balancenet_scrapy_history_update
                params:
                    - id
            view_link:
                type: url
                route: balancenet_scrapy_history_view
                params:
                    - id
            delete_link:
                type: url
                route: oro_api_delete_user
                params:
                    - id
        sorters:
            columns:
                name:
                    data_name: f.message
            default:
                username: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC

        filters:
            columns:

        actions:
            view:
                type:          navigate
                acl_resource:  balancenet_scrapy_history_view
                label:         View
                icon:          user
                link:          view_link
                rowAction:     true
            update:
                type:          navigate
                acl_resource:  balancenet_scrapy_history_update
                label:         Update
                icon:          edit
                link:          update_link
            delete:
                type:          delete
                acl_resource:  balancenet_scrapy_history_delete
                label:         Delete
                icon:          trash
                link:          delete_link
    #Monitor Grid
    monitor-grid:
        extended_entity_name: %balancenet_scrapy.entity.monitor.class%
        options:
            entityHint: monitor
        source:
            acl_resource: oro_user_user_view
            type: orm
            query:
                select:
                    - f.id
                    - f.name
                from:
                    - { table: %balancenet_scrapy.entity.monitor.class%, alias: f }
        columns:
            name:
                label: balanenet.monitor.name.label

        properties:
            id: ~
            update_link:
                type: url
                route: balancenet_scrapy_monitor_update
                params:
                    - id
            view_link:
                type: url
                route: balancenet_scrapy_monitor_view
                params:
                    - id
            delete_link:
                type: url
                route: oro_api_delete_user
                params:
                    - id
        sorters:
            columns:
                name:
                    data_name: f.name
            default:
                username: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC

        filters:
            columns:

        actions:
            view:
                type:          navigate
                acl_resource:  balancenet_scrapy_monitor_view
                label:         View
                icon:          user
                link:          view_link
                rowAction:     true
            update:
                type:          navigate
                acl_resource:  balancenet_scrapy_monitor_update
                label:         Update
                icon:          edit
                link:          update_link
            delete:
                type:          delete
                acl_resource:  balancenet_scrapy_monitor_delete
                label:         Delete
                icon:          trash
                link:          delete_link