oro_menu_config:
    items:
        balancenet_scrapy_tab:
            label: Scrapy
            uri: '#'
        scraped_obj_class_list:
            label: balancenet.scrapedobjclass.menu_label
            route: balancenet_scrapy_scrapedobjclass_index
            extras:
                routes: ['balancenet_scrapy_scrapeobjclass*']
                description: List of pages
        scraper_list:
            label: balancenet.scraper.menu_label
            route: balancenet_scrapy_scraper_index
            extras:
                routes: ['balancenet_scrapy_scraper*']
                description: List of pages
        site_list:
            label: balancenet.site.menu_label
            route: balancenet_scrapy_site_index
            extras:
                routes: ['balancenet_scrapy_site*']
                description: List of pages
        scraping_schedulerruntime:
            label: balancenet.schedulerruntime.menu_label
            route: balancenet_scrapy_schedulerruntime_index
            extras:
                routes: ['balancenet_scrapy_schedulerruntime*']
                description: Scraping Scheduler Runtime
        scraping_monitor:
            label: balancenet.monitor.menu_label
            route: balancenet_scrapy_monitor_index
            extras:
                routes: ['balancenet_scrapy_monitor*']
                description: Scraping Monitor
        scraping_history:
            label: balancenet.history.menu_label
            route: balancenet_scrapy_history_index
            extras:
                routes: ['balancenet_scrapy_history*']
                description: Scraping History
    tree:
        application_menu:
            children:
                balancenet_scrapy_tab:
                    children:
                        scraped_obj_class_list:
                        scraper_list:
                        site_list:
                        scraping_schedulerruntime:
                        scraping_monitor:
                        scraping_history:
#                            children:
#                                franchisee_list: ~
##        shortcuts:
##            children:
##                shortcut_franchisee_create: ~
##                shortcut_franchisee_list: ~