oro_menu_config:
    items:
        balancenet_scrapy_tab:
            label: Scrapy
            uri: '#'

        scraper_list:
            label: balanenet.scraper.entity_plural_label
            route: balancenet_scrapy_scraper_index
            extras:
                routes: ['balancenet_scrapy_scraper*']
                description: List of pages
    tree:
        application_menu:
            children:
                balancenet_scrapy_tab:
                    children:
                        scraper_list:
#                            children:
#                                franchisee_list: ~
##        shortcuts:
##            children:
##                shortcut_franchisee_create: ~
##                shortcut_franchisee_list: ~