parameters:
  balancenet_scrapy.entity.scraper.class: Balancenet\Bundle\ScrapyBundle\Entity\Scraper

  balancenet_scrapy.event_listener.datagrid.scrapy_scraper_listener.class: Balancenet\Bundle\ScrapyBundle\EventListener\Datagrid\ScraperListener

services:

    balancenet_scrapy.scraper:
        class: %balancenet_scrapy.entity.scraper.class%
        #arguments: [@service_id, "plain_value", %parameter%]

